-- MySQL Script generated by MySQL Workbench
-- Thu Oct 11 20:56:00 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema petsmeeting
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema petsmeeting
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `petsmeeting` DEFAULT CHARACTER SET utf8 ;
USE `petsmeeting` ;

-- -----------------------------------------------------
-- Table `petsmeeting`.`perfil`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `petsmeeting`.`perfil` (
  `idperfil` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  `ativo` INT NULL,
  PRIMARY KEY (`idperfil`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `petsmeeting`.`localizacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `petsmeeting`.`localizacao` (
  `idlocalizacao` INT NOT NULL AUTO_INCREMENT,
  `lagitude` VARCHAR(300) NULL,
  `longitude` VARCHAR(300) NULL,
  PRIMARY KEY (`idlocalizacao`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `petsmeeting`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `petsmeeting`.`Usuario` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  `email` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(45) NULL,
  `ativo` VARCHAR(45) NULL,
  `fk_idperfil` INT NOT NULL,
  `fk_idlocalizacao` INT NOT NULL,
  `data_criacao` DATE NULL,
  PRIMARY KEY (`idUsuario`),
  INDEX `fk_Usuario_perfil1_idx` (`fk_idperfil` ASC) ,
  INDEX `fk_Usuario_localizacao1_idx` (`fk_idlocalizacao` ASC) ,
  CONSTRAINT `fk_Usuario_perfil1`
    FOREIGN KEY (`fk_idperfil`)
    REFERENCES `petsmeeting`.`perfil` (`idperfil`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Usuario_localizacao1`
    FOREIGN KEY (`fk_idlocalizacao`)
    REFERENCES `petsmeeting`.`localizacao` (`idlocalizacao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `petsmeeting`.`tipo_animal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `petsmeeting`.`tipo_animal` (
  `idtipo_animal` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  PRIMARY KEY (`idtipo_animal`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `petsmeeting`.`animal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `petsmeeting`.`animal` (
  `idanimais` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  `ativo` INT NULL,
  `peso` FLOAT NULL,
  `altura` FLOAT NULL,
  `ano_nascimento` YEAR(4) NULL,
  `apelido` VARCHAR(45) NULL,
  `fk_idtipo_animal` INT NOT NULL,
  `fk_idUsuario` INT NOT NULL,
  `fk_idperfil` INT NOT NULL,
  PRIMARY KEY (`idanimais`),
  INDEX `fk_animais_tipo_animal1_idx` (`fk_idtipo_animal` ASC) ,
  INDEX `fk_animais_perfil1_idx` (`fk_idperfil` ASC) ,
  INDEX `fk_animais_Usuario1_idx` (`fk_idUsuario` ASC) ,
  CONSTRAINT `fk_animais_tipo_animal1`
    FOREIGN KEY (`fk_idtipo_animal`)
    REFERENCES `petsmeeting`.`tipo_animal` (`idtipo_animal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_animais_perfil1`
    FOREIGN KEY (`fk_idperfil`)
    REFERENCES `petsmeeting`.`perfil` (`idperfil`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_animais_Usuario1`
    FOREIGN KEY (`fk_idUsuario`)
    REFERENCES `petsmeeting`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `petsmeeting`.`racas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `petsmeeting`.`racas` (
  `idracas` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  `ativo` INT NULL,
  PRIMARY KEY (`idracas`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `petsmeeting`.`tipo_fotos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `petsmeeting`.`tipo_fotos` (
  `idtipo_fotos` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  `ativo` INT NULL,
  PRIMARY KEY (`idtipo_fotos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `petsmeeting`.`fotos_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `petsmeeting`.`fotos_usuario` (
  `idfotos` INT NOT NULL,
  `diretorio` VARCHAR(200) NULL,
  `ativo` INT NULL,
  `fk_idtipo_fotos` INT NOT NULL,
  `fk_idUsuario` INT NOT NULL,
  PRIMARY KEY (`idfotos`),
  INDEX `fk_fotos_tipo_fotos1_idx` (`fk_idtipo_fotos` ASC) ,
  INDEX `fk_fotos_Usuario1_idx` (`fk_idUsuario` ASC) ,
  CONSTRAINT `fk_fotos_tipo_fotos1`
    FOREIGN KEY (`fk_idtipo_fotos`)
    REFERENCES `petsmeeting`.`tipo_fotos` (`idtipo_fotos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_fotos_Usuario1`
    FOREIGN KEY (`fk_idUsuario`)
    REFERENCES `petsmeeting`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `petsmeeting`.`conteudo_notificacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `petsmeeting`.`conteudo_notificacao` (
  `idnotificacao` INT NOT NULL AUTO_INCREMENT,
  `conteudo` VARCHAR(300) NULL,
  `ativo` INT NULL,
  `id_destino` INT NULL,
  PRIMARY KEY (`idnotificacao`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `petsmeeting`.`Mensagem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `petsmeeting`.`Mensagem` (
  `idMensagem` INT NOT NULL AUTO_INCREMENT,
  `mensagem` LONGTEXT NULL,
  `ativo` INT NULL,
  `id_destinatario` VARCHAR(45) NULL,
  `Conversa_idConversa` INT NOT NULL,
  `data` DATETIME NULL,
  PRIMARY KEY (`idMensagem`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `petsmeeting`.`conversa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `petsmeeting`.`conversa` (
  `Usuario_Usuario` INT NOT NULL,
  `Mensagem_idMensagem` INT NOT NULL,
  `id_destinatario` INT NULL,
  PRIMARY KEY (`Usuario_Usuario`, `Mensagem_idMensagem`),
  INDEX `fk_Usuario_has_Mensagem_Mensagem1_idx` (`Mensagem_idMensagem` ASC) ,
  INDEX `fk_Usuario_has_Mensagem_Usuario1_idx` (`Usuario_Usuario` ASC) ,
  CONSTRAINT `fk_Usuario_has_Mensagem_Usuario1`
    FOREIGN KEY (`Usuario_Usuario`)
    REFERENCES `petsmeeting`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Usuario_has_Mensagem_Mensagem1`
    FOREIGN KEY (`Mensagem_idMensagem`)
    REFERENCES `petsmeeting`.`Mensagem` (`idMensagem`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `petsmeeting`.`tipo_notificacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `petsmeeting`.`tipo_notificacao` (
  `idtipo_notificacao` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(200) NULL,
  PRIMARY KEY (`idtipo_notificacao`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `petsmeeting`.`notificacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `petsmeeting`.`notificacao` (
  `Usuario_idUsuario` INT NOT NULL AUTO_INCREMENT,
  `notificacao_idnotificacao` INT NOT NULL,
  `fk_idtipo_notificacao` INT NOT NULL,
  PRIMARY KEY (`Usuario_idUsuario`, `notificacao_idnotificacao`),
  INDEX `fk_Usuario_has_notificacao_notificacao1_idx` (`notificacao_idnotificacao` ASC) ,
  INDEX `fk_Usuario_has_notificacao_Usuario1_idx` (`Usuario_idUsuario` ASC) ,
  INDEX `fk_Usuario_notificacao_tipo_notificacao1_idx` (`fk_idtipo_notificacao` ASC) ,
  CONSTRAINT `fk_Usuario_has_notificacao_Usuario1`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `petsmeeting`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Usuario_has_notificacao_notificacao1`
    FOREIGN KEY (`notificacao_idnotificacao`)
    REFERENCES `petsmeeting`.`conteudo_notificacao` (`idnotificacao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Usuario_notificacao_tipo_notificacao1`
    FOREIGN KEY (`fk_idtipo_notificacao`)
    REFERENCES `petsmeeting`.`tipo_notificacao` (`idtipo_notificacao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `petsmeeting`.`solicitacao_senha`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `petsmeeting`.`solicitacao_senha` (
  `idsolicitacao_senha` INT NOT NULL AUTO_INCREMENT,
  `url` VARCHAR(45) NULL,
  `ativo` VARCHAR(45) NULL,
  `fk_idUsuario` INT NOT NULL,
  PRIMARY KEY (`idsolicitacao_senha`),
  INDEX `fk_solicitacao_senha_Usuario1_idx` (`fk_idUsuario` ASC) ,
  CONSTRAINT `fk_solicitacao_senha_Usuario1`
    FOREIGN KEY (`fk_idUsuario`)
    REFERENCES `petsmeeting`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `petsmeeting`.`estado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `petsmeeting`.`estado` (
  `idestado` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `ativo` INT NULL,
  PRIMARY KEY (`idestado`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `petsmeeting`.`cidade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `petsmeeting`.`cidade` (
  `idcidade` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  `ativo` VARCHAR(45) NULL,
  `fk_idestado` INT NOT NULL,
  PRIMARY KEY (`idcidade`),
  INDEX `fk_cidade_estado1_idx` (`fk_idestado` ASC) ,
  CONSTRAINT `fk_cidade_estado1`
    FOREIGN KEY (`fk_idestado`)
    REFERENCES `petsmeeting`.`estado` (`idestado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `petsmeeting`.`endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `petsmeeting`.`endereco` (
  `idendereco` INT NOT NULL AUTO_INCREMENT,
  `logradouro` VARCHAR(45) NULL,
  `numero` VARCHAR(45) NULL,
  `complemento` VARCHAR(45) NULL,
  `cep` VARCHAR(45) NULL,
  `fk_idcidade` INT NOT NULL,
  `fk_idUsuario` INT NOT NULL,
  PRIMARY KEY (`idendereco`),
  INDEX `fk_endereco_cidade1_idx` (`fk_idcidade` ASC) ,
  INDEX `fk_endereco_Usuario1_idx` (`fk_idUsuario` ASC) ,
  CONSTRAINT `fk_endereco_cidade1`
    FOREIGN KEY (`fk_idcidade`)
    REFERENCES `petsmeeting`.`cidade` (`idcidade`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_endereco_Usuario1`
    FOREIGN KEY (`fk_idUsuario`)
    REFERENCES `petsmeeting`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `petsmeeting`.`encontro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `petsmeeting`.`encontro` (
  `animais_idanimais` INT NOT NULL,
  `animais_idanimais1` INT NOT NULL,
  `ativo` VARCHAR(45) NULL,
  PRIMARY KEY (`animais_idanimais`, `animais_idanimais1`),
  INDEX `fk_animais_has_animais_animais2_idx` (`animais_idanimais1` ASC) ,
  INDEX `fk_animais_has_animais_animais1_idx` (`animais_idanimais` ASC) ,
  CONSTRAINT `fk_animais_has_animais_animais1`
    FOREIGN KEY (`animais_idanimais`)
    REFERENCES `petsmeeting`.`animal` (`idanimais`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_animais_has_animais_animais2`
    FOREIGN KEY (`animais_idanimais1`)
    REFERENCES `petsmeeting`.`animal` (`idanimais`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `petsmeeting`.`log_acesso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `petsmeeting`.`log_acesso` (
  `idlog_acesso` INT NOT NULL AUTO_INCREMENT,
  `ip_usuario` VARCHAR(45) NULL,
  `data` DATE NULL,
  `horario` TIME NULL,
  `Usuario_idUsuario` INT NOT NULL,
  PRIMARY KEY (`idlog_acesso`),
  INDEX `fk_log_acesso_Usuario1_idx` (`Usuario_idUsuario` ASC) ,
  CONSTRAINT `fk_log_acesso_Usuario1`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `petsmeeting`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `petsmeeting`.`fotos_animal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `petsmeeting`.`fotos_animal` (
  `idfotos` INT NOT NULL,
  `diretorio` VARCHAR(200) NULL,
  `ativo` INT NULL,
  `fk_idanimais` INT NOT NULL,
  PRIMARY KEY (`idfotos`),
  INDEX `fk_fotos_animais_animais1_idx` (`fk_idanimais` ASC) ,
  CONSTRAINT `fk_fotos_animais_animais1`
    FOREIGN KEY (`fk_idanimais`)
    REFERENCES `petsmeeting`.`animal` (`idanimais`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `petsmeeting`.`racas_animal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `petsmeeting`.`racas_animal` (
  `racas_idracas` INT NOT NULL,
  `tipo_animal_idtipo_animal` INT NOT NULL,
  PRIMARY KEY (`racas_idracas`, `tipo_animal_idtipo_animal`),
  INDEX `fk_racas_has_tipo_animal_tipo_animal1_idx` (`tipo_animal_idtipo_animal` ASC) ,
  INDEX `fk_racas_has_tipo_animal_racas1_idx` (`racas_idracas` ASC) ,
  CONSTRAINT `fk_racas_has_tipo_animal_racas1`
    FOREIGN KEY (`racas_idracas`)
    REFERENCES `petsmeeting`.`racas` (`idracas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_racas_has_tipo_animal_tipo_animal1`
    FOREIGN KEY (`tipo_animal_idtipo_animal`)
    REFERENCES `petsmeeting`.`tipo_animal` (`idtipo_animal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
